apiVersion: RedirectionService/v1
kind: RedirectionServiceConfig
metadata:
  name: "example config"
spec:
  paramPeeling:
    - host: "888casino.com"
      protocols: [http, https]
      spec:
        params: [
          "ftd",
          "lang"
        ]
    - host: "888poker.com"
      protocols: [http, https]
      configName: "example_config"
  redirections:
    - host: "888casino.com"
      protocols: [http, https]
      configName: ""
    - host: "888casino.com"
      protocols: [http, https]
      configName: ""
