// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redirect.proto

package redirect

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRedirectionMessage struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	RequestID            string   `protobuf:"bytes,2,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	HttpMethod           string   `protobuf:"bytes,4,opt,name=httpMethod,proto3" json:"httpMethod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedirectionMessage) Reset()         { *m = GetRedirectionMessage{} }
func (m *GetRedirectionMessage) String() string { return proto.CompactTextString(m) }
func (*GetRedirectionMessage) ProtoMessage()    {}
func (*GetRedirectionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c17d4fc1876bf7a, []int{0}
}

func (m *GetRedirectionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedirectionMessage.Unmarshal(m, b)
}
func (m *GetRedirectionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedirectionMessage.Marshal(b, m, deterministic)
}
func (m *GetRedirectionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedirectionMessage.Merge(m, src)
}
func (m *GetRedirectionMessage) XXX_Size() int {
	return xxx_messageInfo_GetRedirectionMessage.Size(m)
}
func (m *GetRedirectionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedirectionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedirectionMessage proto.InternalMessageInfo

func (m *GetRedirectionMessage) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *GetRedirectionMessage) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *GetRedirectionMessage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetRedirectionMessage) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

type GetRedirectionResponse struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	HttpStatusCode       int32    `protobuf:"varint,3,opt,name=httpStatusCode,proto3" json:"httpStatusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedirectionResponse) Reset()         { *m = GetRedirectionResponse{} }
func (m *GetRedirectionResponse) String() string { return proto.CompactTextString(m) }
func (*GetRedirectionResponse) ProtoMessage()    {}
func (*GetRedirectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c17d4fc1876bf7a, []int{1}
}

func (m *GetRedirectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedirectionResponse.Unmarshal(m, b)
}
func (m *GetRedirectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedirectionResponse.Marshal(b, m, deterministic)
}
func (m *GetRedirectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedirectionResponse.Merge(m, src)
}
func (m *GetRedirectionResponse) XXX_Size() int {
	return xxx_messageInfo_GetRedirectionResponse.Size(m)
}
func (m *GetRedirectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedirectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedirectionResponse proto.InternalMessageInfo

func (m *GetRedirectionResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GetRedirectionResponse) GetHttpStatusCode() int32 {
	if m != nil {
		return m.HttpStatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRedirectionMessage)(nil), "hobord.redirect.GetRedirectionMessage")
	proto.RegisterType((*GetRedirectionResponse)(nil), "hobord.redirect.GetRedirectionResponse")
}

func init() { proto.RegisterFile("redirect.proto", fileDescriptor_7c17d4fc1876bf7a) }

var fileDescriptor_7c17d4fc1876bf7a = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x55, 0x69, 0xe7, 0x10, 0xcb, 0x80, 0x12, 0x8a, 0x88, 0xe4, 0x50, 0x3d, 0xe5,
	0xa0, 0xff, 0x40, 0x03, 0xd2, 0x43, 0x2f, 0xe9, 0x4d, 0xbc, 0xa4, 0xc9, 0x60, 0x16, 0x4a, 0x26,
	0xee, 0x4c, 0xf4, 0x17, 0xf8, 0xbf, 0x65, 0xd7, 0x6e, 0xb5, 0x41, 0xe8, 0x6d, 0xe7, 0x7b, 0xc3,
	0xbc, 0xc7, 0x5b, 0x88, 0x2d, 0xd5, 0xc6, 0x52, 0xa5, 0x59, 0x67, 0x59, 0x19, 0xcf, 0x1b, 0x5e,
	0xb3, 0xad, 0xb3, 0x80, 0xd3, 0xaf, 0x08, 0x2e, 0x9e, 0x49, 0x8b, 0xed, 0x6c, 0xb8, 0x5d, 0x92,
	0x48, 0xf9, 0x46, 0x78, 0x05, 0x13, 0x21, 0x11, 0xc3, 0xed, 0x22, 0x4f, 0xa2, 0x9b, 0xe8, 0x6e,
	0x52, 0xfc, 0x02, 0xa7, 0x5a, 0x7a, 0xef, 0x49, 0x74, 0x91, 0x27, 0xc7, 0x3f, 0xea, 0x0e, 0xe0,
	0x14, 0x46, 0xbd, 0xdd, 0x24, 0x23, 0xcf, 0xdd, 0x13, 0xaf, 0x01, 0x1a, 0xd5, 0x6e, 0x49, 0xda,
	0x70, 0x9d, 0x9c, 0x78, 0xe1, 0x0f, 0x49, 0x5f, 0xe1, 0x72, 0x3f, 0x46, 0x41, 0xd2, 0x71, 0x2b,
	0x84, 0x33, 0x18, 0x6f, 0xb8, 0x2a, 0x1d, 0xdb, 0xc6, 0xd8, 0xcd, 0x38, 0x87, 0xd8, 0xdd, 0x58,
	0x69, 0xa9, 0xbd, 0x3c, 0x71, 0x4d, 0xde, 0xf2, 0xb4, 0x18, 0xd0, 0xfb, 0x4f, 0x98, 0xe6, 0xe1,
	0xf6, 0x8a, 0xec, 0x87, 0xa9, 0x08, 0x2b, 0x88, 0xf7, 0x1d, 0x71, 0x9e, 0x0d, 0xda, 0xc9, 0xfe,
	0x6d, 0x66, 0x76, 0x7b, 0x60, 0x2f, 0x44, 0x4f, 0x8f, 0x1e, 0xe1, 0x65, 0x1c, 0x96, 0xd6, 0x67,
	0xfe, 0x0b, 0x1e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xe8, 0x9e, 0xab, 0x94, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DRedirectServiceClient is the client API for DRedirectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DRedirectServiceClient interface {
	GetRedirection(ctx context.Context, in *GetRedirectionMessage, opts ...grpc.CallOption) (*GetRedirectionResponse, error)
}

type dRedirectServiceClient struct {
	cc *grpc.ClientConn
}

func NewDRedirectServiceClient(cc *grpc.ClientConn) DRedirectServiceClient {
	return &dRedirectServiceClient{cc}
}

func (c *dRedirectServiceClient) GetRedirection(ctx context.Context, in *GetRedirectionMessage, opts ...grpc.CallOption) (*GetRedirectionResponse, error) {
	out := new(GetRedirectionResponse)
	err := c.cc.Invoke(ctx, "/hobord.redirect.DRedirectService/GetRedirection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DRedirectServiceServer is the server API for DRedirectService service.
type DRedirectServiceServer interface {
	GetRedirection(context.Context, *GetRedirectionMessage) (*GetRedirectionResponse, error)
}

// UnimplementedDRedirectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDRedirectServiceServer struct {
}

func (*UnimplementedDRedirectServiceServer) GetRedirection(ctx context.Context, req *GetRedirectionMessage) (*GetRedirectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedirection not implemented")
}

func RegisterDRedirectServiceServer(s *grpc.Server, srv DRedirectServiceServer) {
	s.RegisterService(&_DRedirectService_serviceDesc, srv)
}

func _DRedirectService_GetRedirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedirectionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRedirectServiceServer).GetRedirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hobord.redirect.DRedirectService/GetRedirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRedirectServiceServer).GetRedirection(ctx, req.(*GetRedirectionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _DRedirectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hobord.redirect.DRedirectService",
	HandlerType: (*DRedirectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRedirection",
			Handler:    _DRedirectService_GetRedirection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redirect.proto",
}
