// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redirect.proto

package redirect

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRedirectionMessage struct {
	SessionID            string            `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	RequestID            string            `protobuf:"bytes,2,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Url                  string            `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	HttpMethod           string            `protobuf:"bytes,4,opt,name=httpMethod,proto3" json:"httpMethod,omitempty"`
	Headers              map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetRedirectionMessage) Reset()         { *m = GetRedirectionMessage{} }
func (m *GetRedirectionMessage) String() string { return proto.CompactTextString(m) }
func (*GetRedirectionMessage) ProtoMessage()    {}
func (*GetRedirectionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c17d4fc1876bf7a, []int{0}
}

func (m *GetRedirectionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedirectionMessage.Unmarshal(m, b)
}
func (m *GetRedirectionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedirectionMessage.Marshal(b, m, deterministic)
}
func (m *GetRedirectionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedirectionMessage.Merge(m, src)
}
func (m *GetRedirectionMessage) XXX_Size() int {
	return xxx_messageInfo_GetRedirectionMessage.Size(m)
}
func (m *GetRedirectionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedirectionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedirectionMessage proto.InternalMessageInfo

func (m *GetRedirectionMessage) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *GetRedirectionMessage) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *GetRedirectionMessage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetRedirectionMessage) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

func (m *GetRedirectionMessage) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type GetRedirectionResponse struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	HttpStatusCode       int32    `protobuf:"varint,3,opt,name=httpStatusCode,proto3" json:"httpStatusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedirectionResponse) Reset()         { *m = GetRedirectionResponse{} }
func (m *GetRedirectionResponse) String() string { return proto.CompactTextString(m) }
func (*GetRedirectionResponse) ProtoMessage()    {}
func (*GetRedirectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c17d4fc1876bf7a, []int{1}
}

func (m *GetRedirectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedirectionResponse.Unmarshal(m, b)
}
func (m *GetRedirectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedirectionResponse.Marshal(b, m, deterministic)
}
func (m *GetRedirectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedirectionResponse.Merge(m, src)
}
func (m *GetRedirectionResponse) XXX_Size() int {
	return xxx_messageInfo_GetRedirectionResponse.Size(m)
}
func (m *GetRedirectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedirectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedirectionResponse proto.InternalMessageInfo

func (m *GetRedirectionResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GetRedirectionResponse) GetHttpStatusCode() int32 {
	if m != nil {
		return m.HttpStatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRedirectionMessage)(nil), "github.com.hobord.redirect.GetRedirectionMessage")
	proto.RegisterMapType((map[string]string)(nil), "github.com.hobord.redirect.GetRedirectionMessage.HeadersEntry")
	proto.RegisterType((*GetRedirectionResponse)(nil), "github.com.hobord.redirect.GetRedirectionResponse")
}

func init() { proto.RegisterFile("redirect.proto", fileDescriptor_7c17d4fc1876bf7a) }

var fileDescriptor_7c17d4fc1876bf7a = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xad, 0xd5, 0x76, 0x94, 0x28, 0x8b, 0x4a, 0x08, 0x22, 0x25, 0x07, 0xe9, 0x69, 0xc1,
	0x78, 0x91, 0x1e, 0x3c, 0x68, 0x45, 0x7b, 0xe8, 0x25, 0xbd, 0x88, 0x78, 0xc9, 0xc7, 0xd0, 0x04,
	0x63, 0x36, 0xee, 0x4e, 0x0a, 0xf9, 0x0f, 0xfe, 0x03, 0xff, 0xac, 0x6c, 0x3e, 0x6a, 0x2b, 0x0a,
	0x7a, 0x9b, 0x79, 0x6f, 0xf6, 0xcd, 0x7b, 0xc3, 0x82, 0x29, 0x31, 0x4a, 0x24, 0x86, 0xc4, 0x73,
	0x29, 0x48, 0x30, 0x7b, 0x91, 0x50, 0x5c, 0x04, 0x3c, 0x14, 0xaf, 0x3c, 0x16, 0x81, 0x90, 0x11,
	0x6f, 0x27, 0x9c, 0x8f, 0x0e, 0x1c, 0xdf, 0x23, 0x79, 0x4d, 0x9f, 0x88, 0x6c, 0x86, 0x4a, 0xf9,
	0x0b, 0x64, 0xa7, 0x30, 0x50, 0xa8, 0x54, 0x22, 0xb2, 0xe9, 0xc4, 0x32, 0x86, 0xc6, 0x68, 0xe0,
	0x7d, 0x01, 0x9a, 0x95, 0xf8, 0x56, 0xa0, 0xa2, 0xe9, 0xc4, 0xea, 0xd4, 0xec, 0x0a, 0x60, 0x87,
	0xd0, 0x2d, 0x64, 0x6a, 0x75, 0x2b, 0x5c, 0x97, 0xec, 0x0c, 0x20, 0x26, 0xca, 0x67, 0x48, 0xb1,
	0x88, 0xac, 0xed, 0x8a, 0x58, 0x43, 0xd8, 0x23, 0xec, 0xc6, 0xe8, 0x47, 0x28, 0x95, 0xd5, 0x1b,
	0x76, 0x47, 0x7b, 0xee, 0x35, 0xff, 0xdd, 0x35, 0xff, 0xd1, 0x31, 0x7f, 0xa8, 0x05, 0xee, 0x32,
	0x92, 0xa5, 0xd7, 0xca, 0xd9, 0x63, 0xd8, 0x5f, 0x27, 0xb4, 0xb7, 0x17, 0x2c, 0x9b, 0x44, 0xba,
	0x64, 0x47, 0xd0, 0x5b, 0xfa, 0x69, 0x81, 0x4d, 0x8e, 0xba, 0x19, 0x77, 0xae, 0x0c, 0xe7, 0x19,
	0x4e, 0x36, 0x57, 0x79, 0xa8, 0x72, 0x91, 0x29, 0x64, 0x36, 0xf4, 0x53, 0x11, 0xfa, 0x1a, 0x6b,
	0xa4, 0x56, 0x3d, 0x3b, 0x07, 0x53, 0x27, 0x9b, 0x93, 0x4f, 0x85, 0xba, 0x15, 0x11, 0x56, 0x87,
	0xe8, 0x79, 0xdf, 0x50, 0xf7, 0xdd, 0x80, 0x83, 0x56, 0x7b, 0x8e, 0x72, 0x99, 0x84, 0xc8, 0x4a,
	0x30, 0x37, 0x37, 0xb2, 0x8b, 0x7f, 0x1f, 0xc2, 0x76, 0xff, 0xfe, 0xa4, 0x0d, 0xe4, 0x6c, 0xdd,
	0xc0, 0x53, 0xbf, 0x1d, 0x0a, 0x76, 0xaa, 0x9f, 0x73, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x1e, 0xa5, 0x0f, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RedirectServiceClient is the client API for RedirectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RedirectServiceClient interface {
	GetRedirection(ctx context.Context, in *GetRedirectionMessage, opts ...grpc.CallOption) (*GetRedirectionResponse, error)
}

type redirectServiceClient struct {
	cc *grpc.ClientConn
}

func NewRedirectServiceClient(cc *grpc.ClientConn) RedirectServiceClient {
	return &redirectServiceClient{cc}
}

func (c *redirectServiceClient) GetRedirection(ctx context.Context, in *GetRedirectionMessage, opts ...grpc.CallOption) (*GetRedirectionResponse, error) {
	out := new(GetRedirectionResponse)
	err := c.cc.Invoke(ctx, "/github.com.hobord.redirect.RedirectService/GetRedirection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedirectServiceServer is the server API for RedirectService service.
type RedirectServiceServer interface {
	GetRedirection(context.Context, *GetRedirectionMessage) (*GetRedirectionResponse, error)
}

// UnimplementedRedirectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRedirectServiceServer struct {
}

func (*UnimplementedRedirectServiceServer) GetRedirection(ctx context.Context, req *GetRedirectionMessage) (*GetRedirectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedirection not implemented")
}

func RegisterRedirectServiceServer(s *grpc.Server, srv RedirectServiceServer) {
	s.RegisterService(&_RedirectService_serviceDesc, srv)
}

func _RedirectService_GetRedirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedirectionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectServiceServer).GetRedirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hobord.redirect.RedirectService/GetRedirection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectServiceServer).GetRedirection(ctx, req.(*GetRedirectionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _RedirectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.hobord.redirect.RedirectService",
	HandlerType: (*RedirectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRedirection",
			Handler:    _RedirectService_GetRedirection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redirect.proto",
}
